name: Continue to Run concurrent Jobs
on: push

jobs:
  job-A:
    runs-on: macos-latest
    strategy:
      matrix:
        jobNumber: [1,2,3]
        timeout: [1, 2]

    timeout-minutes: ${{ matrix.timeout }}
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Echo timeout Value
        run: |
      - name: while loop Job A
        run: while true; do echo "sleep"; sleep 2; done;