name: Continue to Run concurrent Jobs
on: push

jobs:
  job-A:
    runs-on: macos-latest
    timeout-minutes: 2
    strategy:
      matrix:
        jobNumber: [1,2,3]
        timeout: [1, 2]
    env:
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Echo timeout Value
        run: |
          echo matrix.timeout
          ehco matrix.timeout == 2
      - name: while loop Job A
        run: while martrix.timeout == 2 ; do echo "sleep"; sleep 2; done; exit 1